In [3]:
def main(**kwargs):
    for k, v in kwargs.items():
        print(k, v)

In [13]:
main(name="Alice", age=30, city="New York")

{'name': 'Alice', 'age': 30, 'city': 'New York'}


In [12]:
def main(**args):
    print(args)
    

In [11]:
main("Alice", 30,"New York")

('Alice', 30, 'New York')


#### 20.	Write a one-liner that will count the number of capital letters in a file. Your code should work even if the file is too big to fit in memory.

In [16]:
filename = 'file.txt'

In [15]:
with open(filename, 'w') as f:
    f.write("This is the First Line.\n")
    f.write("Here is the Second line!\n")
    f.write("third line with some UPPERCASE letters.\n")
    f.write("Final line, with Numbers 123 and symbols #$%.\n")


In [21]:
sum(1 for line in open(filename, 'r') for char in line if char.isupper())

16

#### 22.	How can you randomize the items of a list in place in Python?

In [22]:
l1 = [1,2,3,4,5]

In [23]:
import random

In [29]:
random.shuffle(l1)
l1

[2, 4, 3, 1, 5]

In [31]:
import dis

# Function to return the sum of recursive numbers
def recursive_sum(n):
	if n <= 1:
		return n
	else:
		return n + recursive_sum(n-1)

# change this value for a different result
number = 40

if number < 0:
	print("The sum = ",recursive_sum(number))

# By using dis module, the bytecode is loaded into machine code, and a piece of code that reads each instruction in the bytecode and executes whatever operation is indicated. 
dis.dis(recursive_sum)

  5           0 LOAD_FAST                0 (n)
              2 LOAD_CONST               1 (1)
              4 COMPARE_OP               1 (<=)
              6 POP_JUMP_IF_FALSE       12

  6           8 LOAD_FAST                0 (n)
             10 RETURN_VALUE

  8     >>   12 LOAD_FAST                0 (n)
             14 LOAD_GLOBAL              0 (recursive_sum)
             16 LOAD_FAST                0 (n)
             18 LOAD_CONST               1 (1)
             20 BINARY_SUBTRACT
             22 CALL_FUNCTION            1
             24 BINARY_ADD
             26 RETURN_VALUE
             28 LOAD_CONST               0 (None)
             30 RETURN_VALUE


### Merge sort

In [371]:
arr = [8, 2, 5, 3, 4, 7, 6, 1]

In [132]:
def merge_sort(arr):
    arr_len = len(arr)
    # base case
    if arr_len <=1:
        return
    
    mid = arr_len//2
    left_arr = arr[:mid]
    right_arr = arr[mid:]

    merge_sort(left_arr)
    merge_sort(right_arr)
    
    print(f"Merging left {left_arr} and right {right_arr}")
    return merge(left_arr, right_arr, arr)
    

In [133]:
def merge(left, right, arr):
    sorted_arr = arr
    i = j = k = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            sorted_arr[k] = left[i]
            i += 1
        else:
            sorted_arr[k] = right[j]
            j += 1
        k += 1

    while i < len(left):
        sorted_arr[k] = left[i]
        i+=1
        k+=1
    while j < len(right):
        sorted_arr[k] = right[j]
        j+=1
        k+=1
    
    return sorted_arr

    

In [134]:
merge_sort(arr)

Merging left [1] and right [2]
Merging left [3] and right [4]
Merging left [1, 2] and right [3, 4]
Merging left [5] and right [6]
Merging left [7] and right [8]
Merging left [5, 6] and right [7, 8]
Merging left [1, 2, 3, 4] and right [5, 6, 7, 8]


[1, 2, 3, 4, 5, 6, 7, 8]

### pickling

In [138]:
import pickle

In [139]:
data = {'name': 'Alice', 'age': 25}
with open('data.pkl', 'wb') as file:
    pickle.dump(data, file)  # Pickling the object

In [143]:
with open('data.pkl', 'rb') as f:
    print(pickle.load(f))
#     print(f.read())

{'name': 'Alice', 'age': 25}


### Mapping

In [242]:
def add_2(n):
    return n + 2

In [243]:
print(list(map(add_2, [1,2,3,4])))

[3, 4, 5, 6]


### Numpy

In [244]:
# get indices for n maximum values in numpy array

In [245]:
import numpy as np

In [246]:
n = 3
arr = np.array([8, 1, 5, 6, 4, 3, 2, 7])

In [247]:
np.argsort(arr)

array([1, 6, 5, 4, 2, 3, 7, 0], dtype=int64)

In [248]:
np.argsort(arr)[-n:]

array([3, 7, 0], dtype=int64)

### 38. calculating percentiles

In [249]:
np.percentile(arr, [25, 50, 75])

array([2.75, 4.5 , 6.25])

In [250]:
data = np.array([10, 20, 30, 40, 50])

In [251]:
np.percentile(data, 50)

30.0

### 40. Use of decorators 

In [252]:
def logger(function):
    def n():
        print("This is a decorator.\nWill execute the function")
        function()
    return n
    

@logger
def main():
    print("Hello world")

In [253]:
main()

This is a decorator.
Will execute the function
Hello world


In [254]:
print(arr)
print(arr+2)
print(arr ** 2)

[8 1 5 6 4 3 2 7]
[10  3  7  8  6  5  4  9]
[64  1 25 36 16  9  4 49]


In [262]:
np.std(arr)

2.29128784747792

In [263]:
n_arr = list(arr)

In [264]:
n_arr.reverse()

In [265]:
print(arr)
print(n_arr)

[8 1 5 6 4 3 2 7]
[7, 2, 3, 4, 6, 5, 1, 8]


In [268]:
n_arr

[7, 2, 3, 4, 6, 5, 1, 8]

In [269]:
n_arr[::-1]

[8, 1, 5, 6, 4, 3, 2, 7]

In [270]:
n_arr

[7, 2, 3, 4, 6, 5, 1, 8]

In [271]:
n_arr.pop()

8

In [272]:
n_arr

[7, 2, 3, 4, 6, 5, 1]

### Find overlapping rectangles

In [289]:
class Point(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __repr__(self):
        return f"X: {self.x}\nY: {self.y}\n"

In [316]:
r1 = [Point(1,6), Point(5,2)]
r2 = [Point(4,8), Point(7,4)]

In [357]:
def overlap(r1, r2):
    r1_p1 = r1[0]
    r1_p2 = r1[1]
    
    r2_p1 = r2[0]
    r2_p2 = r2[1]
    
    if r1_p1.x < r2_p1.x and r1_p2.x > r2_p1.x: # triangle A is on the left of B
        return True
    if r1_p1.x > r2_p1.x and r1_p1.x < r2_p2.x: # if triangle A is on the right of B, check point 1.x of B with point 2.x of A
        return True
    if (r1_p1.y > r2_p1.y and r1_p2.y < r2_p1.y) or (r1_p1.y < r2_p1.y and r1_p1.y > r2_p2.y): # triangle A above triangle B
        return True
    else:
        return False


In [358]:
r1 = [Point(1,7), Point(2,3)]
r2 = [Point(1,4), Point(2,1)]

In [359]:
overlap(r2, r1)

True

### angle between hour and minute hand

```
360 degrees in a clock

hour hand: degrees per hour, 360/12 = 30
hour hand: degrees per minute 30/60 = 0.5
    
min hand: degrees per hour: 360/1 = 360
min hand: degrees per minute: 360/60 = 6```
    

In [368]:
def find_angle(hour, minute):
    hour_degree = (hour * 30) + (minute * 0.5)
    minute_degree = (minute * 6)
    diff = hour_degree - minute_degree
    if diff == 360:
        return 0
    return abs(diff)
    

In [370]:
find_angle(3, 15)

7.5

### counting inversions using merge sort

In [414]:
def merge(left, right, arr):
    inc_count = 0
    sorted_arr = arr
    i = j = k = 0
    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            sorted_arr[k] = left[i]
            i += 1
        else:
            sorted_arr[k] = right[j]
            inc_count += len(left[i-1:])
            j += 1
        k += 1

    while i < len(left):
        sorted_arr[k] = left[i]
        i+=1
        k+=1
    while j < len(right):
        sorted_arr[k] = right[j]
        j+=1
        k+=1
    return sorted_arr, inc_count


In [417]:
def merge_sort(arr):
    inc_count = 0
    arr_len = len(arr)
    # base case
    if arr_len <=1:
        return
    
    mid = arr_len//2
    left_arr = arr[:mid]
    right_arr = arr[mid:]

    merge_sort(left_arr)
    merge_sort(right_arr)
    
#     print(f"Merging left {left_arr} and right {right_arr}")
    sorted_arr, count = merge(left_arr, right_arr, arr)
    inc_count += count
    print(inc_count)
    return merge(left_arr, right_arr, arr)
    

In [418]:
arr = [8, 2, 5, 3, 4, 7, 6, 1]
merge_sort(arr)

1
1
4
0
1
3
8


([1, 2, 3, 4, 5, 6, 7, 8], 8)

### find the missing number

In [27]:
n = 999
arr = list(range(1,n))

In [28]:
arr.remove(185)

In [29]:
i = 0
while i < len(arr)-1:
    if arr[i+1] - arr[i] != 1:
        print(f"missing number {arr[i]+1}")
        break
    i += 1

missing number 185


In [30]:
s = ((n+1)*(n+2))//2
s

500500

In [31]:
sum(arr)

498316

In [32]:
sum(arr) - s

-2184

### x raised to the power n

In [46]:
x = 2
n = 5

In [66]:
def power(x, n):
    total = 1
    for i in range(1,n+1):
        total *= x
    print(total)


In [67]:
power(x,n)

32


#### 69: check if substring exists in a dictionary of words

In [82]:
def word_break(s, word_dict):
    # Initialize a dp array where dp[i] is True if s[0:i] can be segmented
    dp = [False] * (len(s) + 1)
    dp[0] = True  # Empty string can be segmented
    
    for i in range(1, len(s) + 1):
        for j in range(i):
            # Check if s[j:i] is a word and s[0:j] can be segmented
            if dp[j] and s[j:i] in word_dict:
                dp[i] = True
                break  # No need to check further once dp[i] is True
    
    return dp[len(s)]

# Example usage:
s = "leetcode"
word_dict = {"leet", "code"}
print(word_break(s, word_dict))  # Output: True


False
